<template>
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
    variations
</template>